### ISSUE TITLE
Last commit was 7 days ago

### ISSUE THREAD

**Issue by Ms2ger** [speced/bikeshed-data#3]
@tabatkins please check if something broke.

**Comment by tabatkins** [comment]
My work computer, which runs the update process, is turned off while I'm on vacation. Oops!

I'll get this on some infra next week when I'm back. @foolip says Travis can do it 1/day, or Github Actions more frequently. Or I can run it in my personal server, but I'd prefer something more accessible.

**Comment by foolip** [comment]
https://github.com/foolip/bikeshed-tests is an example of a Travis setup for something similar. The cron trigger itself is added in the Travis UI.

https://github.com/tidoust/reffy/pull/157 is a more complex setup with GitHub Actions, but I'd probably recommend that as more future proof, despite GitHub Actions still being in beta.

**Comment by foolip** [comment]
Sent https://github.com/tabatkins/bikeshed-data/pull/4 for GitHub Actions setup, although untested.

**Comment by tabatkins** [comment]
Closing this as my machine is back on, and as soon as my account is turned on for the Actions beta I'll accept #4 and get it on infra too.
