### ISSUE TITLE
Add XR specs

### ISSUE THREAD

**Issue by Manishearth** [speced/bikeshed-data#5]
WebXR has three specs which should be part of the sync process:

 - https://immersive-web.github.io/webxr/ (https://www.w3.org/TR/webxr/)
 - https://immersive-web.github.io/webxr-ar-module/ (no FPWD yet)
 - https://immersive-web.github.io/webxr-gamepads-module/ (no FPWD yet)

**Comment by Manishearth** [comment]
ping @tabatkins

**Comment by Manishearth** [comment]
(We're working on FPWD and hitting broken links which are hard to fix since we want the EDs to link to EDs and WDs to link to WDs and currently we use an anchors list)

**Comment by tabatkins** [comment]
thanks for the ping, added

**Comment by Manishearth** [comment]
Thank you!

**Comment by Manishearth** [comment]
@tabatkins is there a reason as to why webxr-ar-module-1 and webxr-gamepads-module-1 aren't in biblio-keys.json?
