### ISSUE TITLE
Add WebXR layers,  dom-overlay and hit-test specs to data

### ISSUE THREAD

**Issue by cabanier** [speced/bikeshed-data#7]
@tabatkins

**Comment by cabanier** [comment]
https://github.com/immersive-web/layers
https://github.com/immersive-web/dom-overlays
https://github.com/immersive-web/hit-test

**Comment by tabatkins** [comment]
What do you want for the shortnames? Right now they're definitely too generic, so I suppose "webxr-layers", etc?

**Comment by cabanier** [comment]
yes, you can prepend `webxr`
Thanks!

**Comment by tabatkins** [comment]
All done, give them 15-20 minutes to propagate into the database, then `bikeshed update`.

**Comment by Manishearth** [comment]
Is there a reason these aren't in the biblio folder?

**Comment by tabatkins** [comment]
Because they haven't been published anywhere that I draw biblio data from. Because Bikeshed knows about the specs for anchor data, it can synthesize biblio entries for them, but they won't show up in the `spec-data/biblio/` files until they're published at W3C.

**Comment by Manishearth** [comment]
Aha, so they need to be FPWD'd. Gotcha.
